---
  - name: mount
    become: True
    command: mount "{{ sambamount_mountpoint }}"
    tags:
      - skip_ansible_lint

  - name: restart cache
    become: True
    service:
      name: cachefilesd
      state: restarted
      enabled: yes
